### ISSUE TITLE
`bosco run -r service` no longer starts docker dependencies of its dependencies

### ISSUE THREAD

**Issue by tomruttle** [tes/bosco#143]
`app-resource` depends on `infra-mysql` and `service-resource-reviews`. `service-resource-reviews` depends on `infra-redis`.

Running `bosco start -r app-resource` will start `app-resource`, `service-resource-reviews`, and `infra-mysql`, but won't start `infra-redis`.

Bosco v0.5.29
Node v5.10.1

**Comment by dbellizzi** [comment]
I talked with @BorePlusPlus about this.  We thing something broke around bosco 0.5.14, as I think he verified 0.5.13 is working.  Basically, the deps of deps are not started.

app-authentication does not start service-registration
service-payment-gateway does not start infra-mysql or infra-redis
service-resource-reviews does not start infra-redis

etc.

**Comment by tomruttle** [comment]
I'm trying to get a handle on it now. I can confirm that 0.5.20 works...

**Comment by dbellizzi** [comment]
@BorePlusPlus also seemed to think there was a difference in doing:
``cd app-resource; bosco run``
and
``bosco run -r app-resource\$``

**Comment by tomruttle** [comment]
Oh interesting. I'm doing the latter.

**Comment by BorePlusPlus** [comment]
Hello chaps,

There was indeed difference in behaviour introduced by my latest efforts. I have since introduced transitive dependency resolution (328d005). Alas I was relying on it being flushed out with @cliftonc 's DockerUtils job which wasn't published yet (eventhough I was sending telepathic signals to ![clifton](https://dujrsrsgsd3nh.cloudfront.net/img/emoticons/111274/clifton-1430150411.png)).

Let me see if I can push this out.

For curious here are [my notes](https://gist.github.com/BorePlusPlus/2e634ecf5fd51952110327c73e4312dc) of what gets started under what conditions (see RUN LIST sections).

**Comment by BorePlusPlus** [comment]
@tomruttle seems to be happy with new and improved resolution in 0.5.31
