### ISSUE TITLE
`bosco pull-git` should not try to pull 'remote' repos

### ISSUE THREAD

**Issue by bettiolo** [tes/bosco#178]
When a repo is not on the disk, the error message reads like:

```
[12:05:23] Bosco: Doesn't seem to be a git repo: /Users/mbettiolo/Code/resources-team/infra-mongodb
```

We should instead say something like: 

```
Not found on disk: /Users/mbettiolo/Code/resources-team/infra-mongodb
```

Why do we need to clone infra projects that will be run as docker containers?

**Comment by cliftonc** [comment]
Is infra-mongodb part of the team in github?

`Why do we need to clone infra projects that will be run as docker containers?`

You don't, provided the project isn't part of your team in github.

**Comment by bettiolo** [comment]
The projects are not part of the team.

**Comment by cliftonc** [comment]
First of all, `bosco morning` isn't really a command, its a wrapper around a collection of commands you run each morning.

The one causing you problems here is actually `pull-git`.

The line here means if you are in a service, it uses the project dependencies as the repo list (not the team), and tries to `git pull` them all:

https://github.com/tes/bosco/blob/master/commands/pull-git.js#L118

What this should do is filter out the 'remote' repos from the list so that it doesn't try and git pull them.  Will submit a fix.

**Comment by bettiolo** [comment]
@cliftonc I updated the description
