### ISSUE TITLE
bosco install reset when node version is changed

### ISSUE THREAD

**Issue by sithmel** [tes/bosco#219]
I think bosco should store somewhere the version of node used to run npm install or yarn on a package. Then, when it doesn't match, it should remove the node_modules before reinstalling again.

**Comment by cliftonc** [comment]
:+1: this is a good idea, will do this this week.

**Comment by codeaholics** [comment]
Would it be better to warn the user and exit (unless a `-f` flag is specified)? It could be that the user simply has a node version mixup that could be fixed with an `nvm` command, whereas a complete reinstall of modules can be quite a heavyweight process requiring network access. You'd be pretty annoyed if you were sitting on an aeroplane and it removed `node_modules` and then wasn't able to reinstall.
