### ISSUE TITLE
Bundle version location is inconsistent

### ISSUE THREAD

**Issue by tomchambers2** [tes/bosco#70]
We need to be able to reference fonts using relative paths from inside library css files (fontawesome, bootstrap etc). Problem is that the bundle version is not known to the static css file and gets in the way of the relative path. See here:

http://local.tescloud.com:7334/site-assets/main/local/css/lib/bootstrap.min.css

http://local.tescloud.com:7334/site-assets/local/main/font-awesome/fontawesome-webfont.eot

**Comment by cliftonc** [comment]
If it is relative it should always be fine?  I'm not sure I understand ...

```
../../fonts/font-awesome/fontawesome-webfont.eot
```

Would work?

**Comment by tomchambers2** [comment]
That would link to `http://local.tescloud.com:7334/site-assets/main/local/main/font-awesome/fontawesome-webfont.eot`, but needs to be `http://local.tescloud.com:7334/site-assets/local/main/font-awesome/fontawesome-webfont.eot` to work currently - but when the files get linked the bundle version comes before the bundle name.

Changed the fonts bundle name to main for clarity here.

**Comment by cliftonc** [comment]
Sorry - got it ... it will work in minified mode, linked to #68.   e.g. if you run:

```
bosco cdn minify
```

Unfortunately I can't fix this without breaking files can appear in multiple bundle thing from earlier, or massively re-factoring how the static assets work.

Let me give it some thought.

**Comment by cliftonc** [comment]
Apologies for two commits with same message, late in the day.

@tomchambers2 if you can clone from this branch and 'npm link' bosco locally and test with this that would be appreciated.  

There is a lot of change here, and it really exposed some pretty horrible old code I had lying around in the Minify module particularly (that I have left largely untouched but worked around for now).  

The key change is simple, instead of assets being stored in a map with a unique key they are now stored in an array, so deciding on different uniqueness constraints / aggregations is more flexible.  However this was a major rework of the core libs, cdn and s3push - so assistance confirming it works for you + others would be appreciated before I pull.

This does not change the external API in any way.
